#!/bin/bash
#mount "/dev/disk/by-label/XenServer\x20Tools" /mnt
ls /dev
mount /dev/{{ device }} /mnt
cd /mnt/Linux
./install.sh -n

echo "{{ username }} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
mkdir -p ~{{ username }}/.ssh/
echo "{{ pubkey }}" >> ~{{ username }}/.ssh/authorized_keys
chown -R {{ username }}:{{ username }} ~{{ username}}/.ssh
chmod  700 ~{{ username }}/.ssh
chmod -R 600 ~{{ username }}/.ssh/*

